### PR TITLE
Add api to reject withdrawal request

### PR DESCRIPTION
**Pull request by yoojinko**
This pr will be merged after merging #220 with changing param name. 
(WithdrawRequestList -> WithdrawRequestMap)

### CODE REVIEW

**Comment by yoojinko** [comment]
Parameter name and type name was updated.

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Review by woomurf — APPROVED** [review]
LGTM, Thanks!

**Comment by yoojinko** [comment]
Thanks for the reviews!

**Pull request merged**
