### PR TITLE
getTxBody functions & Update readme

### PR DESCRIPTION
**Pull request by woomurf**
- Separate func and getTxBody func.
- Update ainftJs constructor
- Update setAccessKey -> setPrivateKey
- Update README

### CODE REVIEW

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Comment by woomurf** [comment]
setNftMetadata also updated. Could you please review again? Thanks! @platfowner

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Comment by woomurf** [comment]
Thanks for the review!

**Pull request merged**
