### PR TITLE
Change metadata type

### PR DESCRIPTION
**Pull request by ehgmsdk20**
Related PRs:
- https://bitbucket.org/comcomai/nft-server-cloud-functions/pull-requests/37
- https://bitbucket.org/comcomai/nft-server/pull-requests/265

### CODE REVIEW

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Comment by jiyoung-an** [comment]
LGTM, Thanks!

**Review by jiyoung-an — APPROVED** [review]

**Comment by akaster99** [comment]
LGTM, Thanks!

**Review by yoojinko — APPROVED** [review]
LGTM, Thanks!

**Comment by ehgmsdk20** [comment]
Thanks for the reviews~

**Pull request merged**
