### PR TITLE
feat: add name at item history

### PR DESCRIPTION
**Pull request by akastercomcom**
add name field at itemPucrhaseHistory type and itemHistory type

### CODE REVIEW

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Review by yoojinko — APPROVED** [review]
LGTM, Thanks!

**Comment by akastercomcom** [comment]
Thanks! 
now merged!

**Comment by platfowner** [comment]
@akastercomcom BTW, could you set your email public for the github account?
https://github.com/akastercomcom

**Comment by akastercomcom** [comment]
> @akastercomcom BTW, could you set your email public for the github account? https://github.com/akastercomcom

updated, Thanks!

**Comment by platfowner** [comment]
> > @akastercomcom BTW, could you set your email public for the github account? https://github.com/akastercomcom
> 
> updated, Thanks!

thanks!! 👍

**Pull request merged**
