### PR TITLE
Add getUserDepositAddress

### PR DESCRIPTION
**Pull request by yoojinko**
Add new method getUserDepositAddress.

### CODE REVIEW

**Review by woomurf — APPROVED** [review]
LGTM, Thanks!

**Comment by yoojinko** [comment]
depositAddress method was moved from asset to auth. 
PTAL! @woomurf

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Comment by yoojinko** [comment]
Thanks for the reviews!

**Pull request merged**
