### PR TITLE
Feat : change deposit history path

### PR DESCRIPTION
**Pull request by akastercomcom**
- at getDepositHistory, i deleted chain and reset api Path.

### CODE REVIEW

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Comment by platfowner** [comment]
It looks like reviewers are not added. @akastercomcom

**Review by yoojinko — APPROVED** [review]
LGTM, Thanks!

**Comment by akastercomcom** [comment]
Thanks for reviews!
now merged

**Pull request merged**
