### PR TITLE
Add managedContracts-related-apis

### PR DESCRIPTION
**Pull request by ehgmsdk20**
Added APIs for managedContracts that should be performed first before the setNftMetadata call

### CODE REVIEW

**Review by jiyouang — APPROVED** [review]
LGTM, Thanks!

**Review by woomurf — APPROVED** [review]
LGTM, Thanks!

**Review by yoojinko — APPROVED** [review]
LGTM, Thanks!!

**Comment by ehgmsdk20** [comment]
Thanks for the reviews!

**Pull request merged**
