### PR TITLE
Release/0.6.0

### PR DESCRIPTION
**Pull request by woomurf**
#159 
#175 
#176 

Update chain/network and Replace asset class to Credit and Nft class. And Add deposit history func.

### CODE REVIEW

**Review by ehgmsdk20 — APPROVED** [review]
LGTM, thanks!

**Comment by akaster99** [comment]
LGTM, thanks!

**Comment by kriii** [comment]
LGTM, Thanks!

**Review by yoojinko — APPROVED** [review]
LGTM, Thanks!!

**Review by akaster99 — APPROVED** [review]

**Comment by woomurf** [comment]
Thanks for the review!

**Pull request merged**
